### ISSUE TITLE
consider contribution to nixos-aarch64 image

### ISSUE THREAD

**Issue by ghostbuster91** [nakato/nixos-bpir3-example#1]
Hi, thanks for that repo, this is really awesome, and thanks for the prebuild image! 

I was wondering if it would be possible to upstream that build into https://github.com/Mic92/nixos-aarch64-images though I must admit that my knowledge about this stuff is very limited, so it may be as well not a good idea.

**Comment by nakato** [comment]
Part of the stated goal of that repo is to be able to be built on non-aarch64 platforms, and as the current state of the BPi-R3 requires a custom kernel configuration as well as a devicetree overlay (for the SD card) applied we can't modify the generic upstream aarch64 image and get a working image from that.

I'm going to refrain from attempting to add support for this target there as it would be at odds with the stated goals of that repo.

I also would need to work out a way to get the `mt7986-default-bootcmd.patch` into a state that it can be submitted for review upstream.  The patch currently is an ugly hack at best and I expect it's fairly brittle.  Once in an acceptable state, even if it's not something upstream u-boot wants to support it would at least be in a state where I would be okay proposing to including it into nixpkgs.
The disabling of FDT reallocation by setting `FDT_HIGH="0xffffffffffffffff"` is, at the very least, unacceptable.  It was me essentially throwing in the towel after trying to get it to boot the right way for 16 hours.

**Comment by ghostbuster91** [comment]
Understood, thank you for taking your time to write such an insightful answer, it helps me to understand all the nuances better.
