### ISSUE TITLE
Just letting you (and other people) know the kernel config has changed in 6.6

### ISSUE THREAD

**Issue by chayleaf** [nakato/nixos-bpir3-example#10]
`CONFIG_MT7986_WMAC` -> `CONFIG_MT798X_WMAC`

See:

- https://github.com/chayleaf/dotfiles/commit/3891aa6596051cdc7f9fb4d7a87168a3678cc9e8
- https://lore.kernel.org/lkml/ZF-SN-sElZB_g_bA@pidgin.makrotopia.org/
- https://github.com/torvalds/linux/commit/6bad146d162e92174b09522b357b64f8fda95246

**Comment by nakato** [comment]
Thanks for the heads up on this.  I've updated the kernel to 6.6, and tested it on one of my production devices.

Happy new year.
